<a href="https://colab.research.google.com/github/seudonimo/Test/blob/master/1014_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example - MNIST classification

## 1. Preprocess
### Library Import, and Load dataset from MNIST

In [1]:
from keras.datasets import mnist
from keras import models
from keras import layers
from keras.utils import to_categorical

(_train_images, _train_labels), (_test_images, _test_labels) = mnist.load_data()


Using TensorFlow backend.


11493376/11490434 [==============================] - 1s 0us/step


### Normalize images (from 0 to 1)

In [2]:


#Scaling from zero to one
train_images = _train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = _test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

print(train_images.max())
print(test_images.max())


1.0
1.0


### One hot encoding
이 값을keras.np_utils.categorical()을 사용하여 원핫인코딩(One-Hot-Encoding)로 변환한다.

In [3]:
print(_test_labels)
train_labels = to_categorical(_train_labels)
test_labels = to_categorical(_test_labels)
print("after on-hot encoding, \n", test_labels)

[7 2 1 ... 4 5 6]
after on-hot encoding, 
 [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## 2. Modeling and Compile for Network
### Simple Sequential Model

In [4]:

# 모델 정의하기
model = models.Sequential()

model.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
model.add(layers.Dense(10, activation='softmax'))

# 모델 컴파일 하기
model.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])


## 3. Model.fit - Model Training with parameters

In [5]:
# fit() 메서드로 모델 훈련 시키기
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/5





60000/60000 [==============================] - 7s 109us/step - loss: 0.2556 - acc: 0.9264
Epoch 2/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.1014 - acc: 0.9698
Epoch 3/5
60000/60000 [==============================] - 2s 36us/step - loss: 0.0671 - acc: 0.9795
Epoch 4/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.0494 - acc: 0.9848
Epoch 5/5
60000/60000 [==============================] - 2s 36us/step - loss: 0.0358 - acc: 0.9889


## 4. Evaluation with test dataset


In [6]:
#summary of network

model.summary()

# 테스트 데이터로 정확도 측정하기
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('test_loss :', test_loss, 'test_acc : ', test_acc)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________
10000/10000 [==============================] - 0s 48us/step
test_loss : 0.06392024652091786 test_acc :  0.98


In [7]:
!cat $HOME/.keras/keras.json


{
    "epsilon": 1e-07, 
    "floatx": "float32", 
    "image_data_format": "channels_last", 
    "backend": "tensorflow"
}

# Appendix
